/* Display catalog — templates and looks only. No engine, no network, no secrets. */
window.RESUME_VIEW_CATALOG = {
  looks: {
    ink: ["#1c1917", "#44403c", "#1c1917", "full", "plain", "upper", "left", "regular", 0.4],
    graphite: ["#292524", "#57534e", "#44403c", "full", "plain", "upper", "left", "regular", 0.5],
    copper: ["#1c1917", "#57534e", "#9a3412", "accent", "plain", "upper", "left", "regular", 0.35],
    navy: ["#1e293b", "#475569", "#1e3a5f", "accent", "plain", "upper", "left", "regular", 0.45],
    forest: ["#14532d", "#3f6212", "#166534", "accent", "plain", "upper", "left", "regular", 0.35],
    slate: ["#334155", "#64748b", "#475569", "full", "plain", "upper", "left", "regular", 0.4],
    burgundy: ["#1c1917", "#57534e", "#7f1d1d", "accent", "plain", "upper", "left", "regular", 0.3],
    teal: ["#134e4a", "#0f766e", "#0f766e", "accent", "plain", "upper", "left", "regular", 0.4],
    midnight: ["#0c0a09", "#57534e", "#0c0a09", "full", "plain", "upper", "left", "regular", 0.6],
    sand: ["#44403c", "#78716c", "#78350f", "accent", "plain", "upper", "left", "regular", 0.35],
    minimal: ["#1c1917", "#57534e", "#1c1917", "none", "plain", "title", "left", "airy", 0],
    editorial: ["#1c1917", "#44403c", "#1c1917", "full", "plain", "title", "left", "regular", 0.25],
    lined: ["#1c1917", "#44403c", "#1c1917", "double", "plain", "upper", "left", "regular", 0.5],
    centered: ["#1c1917", "#44403c", "#1c1917", "full", "plain", "upper", "center", "regular", 0.8],
    rail: ["#1c1917", "#44403c", "#1e3a5f", "accent", "bar", "upper", "left", "regular", 0.4],
    underscore: ["#1c1917", "#44403c", "#1c1917", "accent", "underline", "upper", "left", "regular", 0.35],
    dense: ["#1c1917", "#44403c", "#1c1917", "full", "plain", "upper", "left", "tight", 0.3],
    airy: ["#1c1917", "#57534e", "#1c1917", "full", "plain", "title", "left", "airy", 0.15],
    executive: ["#1c1917", "#44403c", "#1e3a5f", "full", "plain", "upper", "left", "regular", 1.4],
    scholar: ["#1c1917", "#57534e", "#7f1d1d", "none", "underline", "title", "left", "airy", 0],
  },
  headings: {
    summary: "Professional Summary",
    skills: "Skills",
    experience: "Experience",
    education: "Education",
    certs: "Licenses and certifications",
    languages: "Languages",
    projects: "Projects",
    publications: "Publications",
    volunteer: "Volunteer",
    references: "References",
  },
  templates: {
    "ats-classic": ["summary", "skills", "experience", "education", "certs"],
    "ats-hybrid": ["skills", "summary", "experience", "education", "certs"],
    "compact-onepage": ["summary", "skills", "experience", "education", "certs"],
    "trades-certs": ["certs", "skills", "summary", "experience", "education"],
    "executive-two-page": ["summary", "skills", "experience", "education", "certs", "languages"],
    graduate: ["summary", "education", "projects", "skills", "experience", "certs"],
    "uk-cv": ["summary", "skills", "experience", "education", "certs", "languages", "references"],
    "academic-cv": [
      "summary",
      "education",
      "publications",
      "projects",
      "experience",
      "skills",
      "certs",
      "languages",
      "volunteer",
      "references",
    ],
    "eu-profile": ["summary", "experience", "education", "skills", "languages", "certs", "projects"],
    "ph-cv": ["summary", "certs", "skills", "experience", "education", "languages", "projects", "references"],
  },
  extraHeadings: {
    "executive-two-page": { summary: "Executive summary" },
    graduate: { summary: "Profile" },
    "uk-cv": { summary: "Professional summary", skills: "Key skills", experience: "Work experience" },
    "academic-cv": { summary: "Research profile", experience: "Appointments" },
    "eu-profile": { summary: "Profile", experience: "Work experience" },
    "ph-cv": { summary: "Professional summary", certs: "Licenses, TESDA, and certifications" },
  },
  fonts: {
    helvetica: "sans",
    "source-sans": "sans",
    "ibm-plex-sans": "sans",
    lato: "sans",
    "open-sans": "sans",
    times: "serif",
    "source-serif": "serif",
    "ibm-plex-serif": "serif",
    baskerville: "serif",
    lora: "serif",
    garamond: "serif",
    crimson: "serif",
    courier: "mono",
  },
};
